from __future__ import annotations

from typing import Protocol

from govlexops.schemas.legal_document import LegalDocument


class DocumentStore(Protocol):
    def append(self, docs: list[LegalDocument]) -> int: ...
    def load_all(self) -> list[dict]: ...
    def query(self, **filters) -> list[dict]: ...
    def count(self) -> dict: ...
